# Generated by Django 4.0.2 on 2022-03-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timedate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taketime',
            name='moorningOrafter',
            field=models.BooleanField(default=True),
        ),
    ]
