# Generated by Django 4.0.2 on 2022-03-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timedate', '0002_taketime_moorningorafter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taketime',
            name='time',
            field=models.CharField(choices=[('8-9', '8-9'), ('9-10', '9-10'), ('10-11', '10-11'), ('11-12', '11-12'), ('15-16', '15-16'), ('16-17', '16-17'), ('17-18', '17-18')], max_length=50),
        ),
    ]
