# Generated by Django 4.0.2 on 2022-03-07 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_company_email_alter_company_first_name_and_more'),
        ('info', '0002_person_user_alter_person_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_company', to='company.company'),
        ),
    ]
