# Generated by Django 4.0.2 on 2022-03-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sick', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infosick',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='infosick',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
