# Generated by Django 4.0.2 on 2022-03-16 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_expertise'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expertise',
        ),
    ]
