# Generated by Django 4.0.2 on 2022-03-16 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_expertise'),
    ]

    operations = [
        migrations.AddField(
            model_name='infodoctor',
            name='expertise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expertise_dr', to='doctor.expertise'),
        ),
    ]
